### ISSUE TITLE
Thanks 👋

### ISSUE THREAD

**Issue by Inventsable** [tokyosheep/IllustratorEventManager#1]
No issues, just wanted to drop by and say thanks for posting this because I'd always been curious about AIHostAdapter but given how difficult it is to find documentation for (especially the JS file) I'd never gotten the chance to try it. Had a peek at your code here and was able to integrate it into a new panel of mine which is great, allows me to do far more with subscribing to certain events instead of always relying on the user interacting with the panel.

**Comment by tokyosheep** [comment]
thank you for posting your comment. I'm delighted that my code helps you.
now I added appendix for developer on readme.
